# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.0

definitions:
  steps:
    - step: &install_and_test
        name: Install Deps and Test
        caches:
          - node
        artifacts:
          - node_modules/**
        script:
          - npm install

    - step: &build_and_deploy
        name: Build and Deploy
        deployment: Test
        script:
          - export BUILD_TIME=$(date)
          - apt-get update && apt-get install -y gettext-base
          - envsubst < .env.pipelines.deploy > .env
          - tail .env
          - npm run build
          - pipe: atlassian/rsync-deploy:0.4.3
            variables:
              USER: 'ubuntu'
              SERVER: '$SERVER_HOST'
              REMOTE_PATH: '$SERVER_PATH'
              LOCAL_PATH: 'build/'
              EXTRA_ARGS: '--exclude-from=deployment-exclude.txt --delete'


pipelines:
  branches:
    #    dev:
    #      - step: *install_and_test
    #      - step: *build_and_deploy

    master:
      - step: *install_and_test
      - step:
          <<: *build_and_deploy
          deployment: Test

