export const CLAIM_STATUS_PENDING = 'Pending'
export const CLAIM_STATUS_APPROVED = 'Approved'
export const CLAIM_STATUS_AWAITING_PAYMENT = 'awaiting payment'
export const CLAIM_STATUS_COMPLETED = 'completed'
export const CLAIM_STATUS_REJECTED = 'declined'
